### PR TITLE
The background image no longer reverse

### PR DESCRIPTION
**Pull request by LucGzy**
Sorry for previous pull request, missed something when testing. here is the change : 
```
.main-container {
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
  width: clamp(200px, 70%, 800px);
  height: 80vh;
  background: url(https://picsum.photos/seed/mvdfsdm/319/436) no-repeat center;
  background-size: cover;
  border-radius: 10px;
  overflow: hidden;
  position: relative;
}

.main-container::before {
  content: "";
  position: absolute;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
  background: linear-gradient(to bottom, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.6));
  z-index: 0;
}

.nightowl-dark .main-container {
  filter: invert(100%) hue-rotate(180deg);
}

.nightowl-dark .correct-invert > * {
  filter: invert(100%) hue-rotate(180deg);
}
```

i added "correct-invert" as a class to target parts that needs to be inverted within main container

### CODE REVIEW

**Comment by PranshuBasak** [comment]
Hi @Likzy , I appreciate your effort in correcting my web page. 
But after viewing the website in action, there is one thing I did not plan, which is that the background is not producing enough contrast for the text while in dark mode.

image
image


The inverted image may look different, but still, it kind of balances out the contrast for its foreground content.

image
image

So I decided to leave this site as it is for now. 
Yet, I want to know what your thoughts are before closing this merger.

**Comment by LucGzy** [comment]
I also noticed the same thing during testing and I overall think that dark mode should only apply to the background and not your actual main-container as it will inevitably make readability worse no matter how we twist it. I would suggest making a custom background rather than the color gradient you have right now, for example, use a dark background with a white shadow on the main-container in dark mode and a light background with a drak shadow in light mode. (Overall nightowl is a bit overkill for the actual page and you could probably make something by yourself like the example i gave without much trouble). Also on an unrelated note : you should try to adapt your code so that your text areas aren't all ```<div>``` tags but rather actual semantic tags for better practices, accessibility and readability.

**Comment by LucGzy** [comment]
Also noticed your API key is in clear in the public code on Github, for this, this is obviously not a risk i'd say but keep in mind to usually remove your keys from public repos because once it has been published it is very hard to fully remove so you usually need to kill the key and ask for a new one.

**Comment by PranshuBasak** [comment]
> Also noticed your API key is in clear in the public code on Github, for this, this is obviously not a risk i'd say but keep in mind to usually remove your keys from public repos because once it has been published it is very hard to fully remove so you usually need to kill the key and ask for a new one.

Yes u r are absolutely right about api being public , Thanks for pointing out I will be making changes accordingly .

**Pull request closed without merging**
